import Head from 'next/head'
import Image from 'next/image'
import NavBar from "../components/Navbar";
import {Card} from "../components/Card";

export default function Home() {
  return (
    <div className="bg-leaf-800 min-h-screen p-6">
      <Head>
        <title>Releaf The Planet</title>
        <meta name="description" content="Calculation of Carbon Footprint" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-Opensans bg-leaf-100 rounded-lg">
        <NavBar/>
        <div className="flex items-center my-6 flex-wrap">
          <div className="w-2/5 p-8">
            <h1 className="text-4xl font-bold text-leaf-800">
              Calculate your FootPrint & Protect our Planet
            </h1>
            <p className="text-lg text-leaf-800 my-8">A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
              A building carbon footprint is defined as the amount of CO2 it produces during its operations and activities. Considering a buildings carbon footprint is something that affects both new construction as well as existing buildings</p>
            <div>
              <div className="flex flex-wrap">
                <Card/>
                <Card/>
              </div>
            </div>
          </div>
          <div className="w-3/5">
            <Image
              src="/leaf-bg.png"
              alt="Environmental place Freepik"
              width={1800}
              height={1200}
            />
          </div>
        </div>
      </main>

    </div>
  )
}
