import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div className="bg-leaf-800 min-h-screen p-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-8 font-Opensans flex bg-leaf-100 rounded-lg">
        <div className="w-1/2">
          <h1 className="text-4xl font-bold text-leaf-800 my-12">
            Calculate your FootPrint & Protect our Planet
          </h1>
          <p className="text-lg text-leaf-700">A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
            A building's carbon footprint is defined as the amount of CO2 it produces during its operations and activities. Considering a building's carbon footprint is something that affects both new construction as well as existing buildings</p>
          <div>
            <p>Card 1</p>
            <p>Card 2</p>
          </div>
        </div>
        <div className="w-1/2">
          <Image
            src="/leaf-bg.png"
            alt="Picture of the author"
            width={1800}
            height={1200}
          />
        </div>
      </main>

    </div>
  )
}
