import Head from 'next/head'
import Image from 'next/image'
import {Card} from "../components/Card";
import Layout from "../components/Layout";

export default function Home() {
  return (
    <div>
      <Layout>
        <main>
          <div className="flex items-center my-2 flex-wrap">
            <div className="w-full p-6 pt-2 md:w-2/5">
              <h1 className="text-4xl font-bold text-leaf-800">
                Calculate your FootPrint & Protect our Planet
              </h1>
              <p className="text-xl text-leaf-800 font-bold my-5">Did you know that for the average person in the Netherlands CO2 compensation is only €250 per year?</p>
              <p className="text-md text-leaf-800 my-8">A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
                A building carbon footprint is defined as the amount of CO2 it produces during its operations and activities. Considering a buildings carbon footprint is something that affects both new construction as well as existing buildings</p>
              <div>
              <Card/>
              </div>
            </div>
            <div className="w-3/5 hidden md:block">
              <Image
                src="/leaf-bg.png"
                alt="Environmental place Freepik"
                width={1800}
                height={1200}
              />
            </div>
          </div>
        </main>
      </Layout>
    </div>
  )
}
